####################################################
#
# Welcome to Levert Jekyll Template
#
# Product Link :  
# Version : v1.0.0
#
####################################################

# Site settings
title: "Puhuri.io"
email: "puhuri@puhuri.io"
baseurl: "" # the subpath of your site, e.g. /blog
url: " " # the base hostname & protocol for your site, e.g. http://example.com
logo: /assets/images/header-brand.png
description: "Puhuri — HPC allocation and provisioning service"
top_letest_news: true
keywords: "puhuri, hpc, LUMI, allocation"
#mailchimp: "https://themeix.us16.list-manage.com/subscribe/post?u=307862c135e4548eecf86f389&amp;id=4784863884"
#facebook: https://facebook.com/themeix
#instagram: https://instagram.com/themeix
#twitter: https://twitter.com/themeix_com
#pinterest: https://pinterest.com/themeix

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-seo-tag


# Site configuration for the Jekyll 2 Pagination Gem
pagination:
  enabled: true
  debug: true
  collection: "posts"
  per_page: 10
  permalink: "/pages/:num/" # Pages are simple html files
  title: ":title - page :num"
  limit: 0
  sort_field: "date"
  sort_reverse: true
  category: "posts"
  tag: ""
  locale: ""
  trail:
    before: 2
    after:
  extension: "html"
  indexpage: "index"

autopages:
  enabled: true
  categories:
    layouts:
      - "category.html"
    title: ":cat"
    permalink: "/category/:cat"
  collections:
    layouts:
      - "category.html"
    title: " :coll" # :coll is replaced by the collection name
    permalink: "/:coll/"

  tags:
    layouts:
      - "tag.html"
    title: ":tag" # :tag is replaced by the tag name
    permalink: "/tag/:tag"

tag_page_layout: category
tag_page_dir: tag
tag_permalink_style: pretty

    
collections:
  authors:
    output: true
    permalink: /author/:path/
  features:
    output: true
    permalink: /feature/:path/

feed:
  collections:
    posts:
      path: "/index.xml"