name: Publish to GitHub Pages branch

on:
  push:
    branches:
      - master

jobs:
  jekyll-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Use GitHub Actions' cache to shorten build times and decrease load on servers
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Setup Pages
      uses: actions/configure-pages@v5

    # Build an artefact
    - name: Build
      uses: actions/jekyll-build-pages@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
  deploy:
    runs-on: ubuntu-latest
    needs: jekyll-build
    permissions:
      actions: read
      checks: read
      contents: read
      deployments: write
      issues: read
      discussions: read
      packages: read
      pages: write
      pull-requests: read
      repository-projects: read
      security-events: read
      statuses: read
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
